swagger: '2.0'
info:
  version: '1.0'
  title: Cubo
  contact: {}
  description: ''
host: 'localhost:5000'
securityDefinitions: {}
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /health:
    get:
      summary: Health
      tags:
        - Misc
      operationId: Health
      deprecated: false
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      security: []
  /pokemon:
    post:
      summary: Save Pokemon
      tags:
        - Misc
      operationId: SavePokemon
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: false
          default: 'Bearer {token}'
          type: string
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/SavePokemonRequest'
      responses:
        '200':
          description: ''
          headers: {}
  '/pokemon/{idPokemon}':
    put:
      summary: Update Pokemon
      tags:
        - Misc
      operationId: UpdatePokemon
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: false
          default: 'Bearer {token}'
          type: string
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/UpdatePokemonRequest'
      responses:
        '200':
          description: ''
          headers: {}
    delete:
      summary: Delete Pokemon
      tags:
        - Misc
      operationId: DeletePokemon
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: false
          default: 'Bearer {token}'
          type: string
        - name: Authorization
          in: query
          required: true
          type: string
          description: ''
      responses:
        '200':
          description: ''
          headers: {}
    parameters:
      - type: string
        name: idPokemon
        in: path
        required: true
  /rol:
    post:
      summary: Create Rol
      tags:
        - Misc
      operationId: CreateRol
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: false
          default: 'Bearer {token}'
          type: string
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/CreateRolRequest'
      responses:
        '200':
          description: ''
          headers: {}
  /user:
    post:
      summary: Register User
      tags:
        - Misc
      operationId: RegisterUser
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: false
          default: 'Bearer {token}'
          type: string
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/RegisterUserRequest'
      responses:
        '200':
          description: ''
          headers: {}
  /auth/login:
    post:
      summary: Login
      tags:
        - Misc
      operationId: Login
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            description: ''
            type: object
            properties:
              username:
                type: string
                minLength: 1
              password:
                type: string
                minLength: 1
            required:
              - username
              - password
            x-examples:
              example-1:
                username: srizo
                password: '123'
      responses:
        '200':
          description: ''
          headers: {}
        '201':
          description: Created
          schema:
            type: object
            properties: {}
        '400':
          description: Bad Request
          schema:
            description: ''
            type: object
            properties:
              message:
                type: string
                minLength: 1
              token:
                type: string
                minLength: 1
              user:
                type: object
                properties:
                  _id:
                    type: string
                    minLength: 1
                  firstName:
                    type: string
                    minLength: 1
                  lastName:
                    type: string
                    minLength: 1
                  username:
                    type: string
                    minLength: 1
                  password:
                    type: string
                    minLength: 1
                  email:
                    type: string
                    minLength: 1
                  rol:
                    type: string
                    minLength: 1
                  __v:
                    type: number
                required:
                  - _id
                  - firstName
                  - lastName
                  - username
                  - password
                  - email
                  - rol
                  - __v
            required:
              - message
              - token
              - user
            x-examples:
              example-1:
                message: Authorized
                token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjUzNDUzMzMsImRhdGEiOnsidXNlcm5hbWUiOiJzcml6byIsInJvbCI6IjYwZGY4NGI2ZWNiNzBlNjFmOGJlZDc0ZSJ9LCJpYXQiOjE2MjUzNDE3MzN9.OrrLbHOtlRP7b8ubqcdtRC1K-eYRsXV7ua86NGbLwxA
                user:
                  _id: 60df8a06a3dbb948d0575b8d
                  firstName: Stefhanie
                  lastName: Rizo
                  username: srizo
                  password: $2b$10$p3QVLq16WGKKmp5eEMMYwuOR5EycXTYt7yEBtj7hTTAG1j9YIgOkK
                  email: stefhanie.rizo@gmail.com
                  rol: 60df84b6ecb70e61f8bed74e
                  __v: 0
definitions:
  SavePokemonRequest:
    title: SavePokemonRequest
    example:
      name: Bulbasaur
      type: Semilla
      powerLevel: 1
    type: object
    properties:
      name:
        type: string
      type:
        type: string
      powerLevel:
        type: integer
        format: int32
    required:
      - name
      - type
      - powerLevel
  UpdatePokemonRequest:
    title: UpdatePokemonRequest
    example:
      powerLevel: 125
    type: object
    properties:
      powerLevel:
        type: integer
        format: int32
    required:
      - powerLevel
  CreateRolRequest:
    title: CreateRolRequest
    example:
      name: Admin
      options:
        - path: /pokemon/create
          method: POST
    type: object
    properties:
      name:
        type: string
      options:
        type: array
        items:
          $ref: '#/definitions/Option'
    required:
      - name
      - options
  Option:
    title: Option
    example:
      path: /pokemon/create
      method: POST
    type: object
    properties:
      path:
        type: string
      method:
        type: string
    required:
      - path
      - method
  RegisterUserRequest:
    title: RegisterUserRequest
    example:
      firstName: Stefhanie
      lastName: Rizo
      username: srizo
      password: '123'
      email: stefhanie.rizo@gmail.com
      rol: 60df84b6ecb70e61f8bed74e
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      username:
        type: string
      password:
        type: string
      email:
        type: string
      rol:
        type: string
    required:
      - firstName
      - lastName
      - username
      - password
      - email
      - rol
  LoginRequest:
    title: LoginRequest
    example:
      username: srizo
      password: '123'
    type: object
    properties:
      username:
        type: string
      password:
        type: string
    required:
      - username
      - password
tags:
  - name: Misc
    description: ''
x-extension-1: null
